image:
  pullPolicy: IfNotPresent
  repository: duplicati/duplicati
  tag: latest
persistence:
  config:
    enabled: true
    mountPath: /data
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 8200
        targetPort: 8200
workload:
  main:
    podSpec:
      containers:
        main:
          env: {}
          probes:
            liveness:
              path: /
              type: http
            readiness:
              path: /
              type: http
            startup:
              path: /
              type: http
