image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/linuxserver/smokeping
  tag: latest
persistence:
  config:
    enabled: true
    mountPath: /config
  data:
    enabled: true
    mountPath: /data
  varrun:
    enabled: false
portal:
  open:
    enabled: true
securityContext:
  container:
    allowPrivilegeEscalation: true
    capabilities:
      add:
      - NET_RAW
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10030
        targetPort: 80
strategy:
  type: Recreate
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
