image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/onedr0p/theme-park
  tag: rolling
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 10244
        targetPort: 8080
