annotations:
  truecharts.org/category: metrics
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: Speedtest Exporter made in python using the official speedtest bin
home: https://truecharts.org/charts/stable/speedtest-exporter
icon: https://truecharts.org/img/hotlink-ok/chart-icons/speedtest-exporter.webp
keywords:
- speedtest-exporter
- speedtest
- metrics
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: speedtest-exporter
sources:
- https://ghcr.io/miguelndecarvalho/speedtest-exporter
- https://github.com/MiguelNdeCarvalho/speedtest-exporter/
- https://github.com/truecharts/charts/tree/master/charts/stable/speedtest-exporter
type: application
version: 2025.1.26
