annotations:
  truecharts.org/category: Other
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: Simple recipes in Markdown format.
home: https://truecharts.org/charts/stable/chowdown
icon: https://truecharts.org/img/hotlink-ok/chart-icons/chowdown.webp
keywords:
- chowdown
- Other
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: chowdown
sources:
- https://github.com/truecharts/charts/tree/master/charts/stable/chowdown
- https://hub.docker.com/r/gregyankovoy/chowdown
type: application
version: 2025.1.26
