image:
  pullPolicy: IfNotPresent
  repository: gregyankovoy/chowdown
  tag: latest
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 4000
        protocol: tcp
        targetPort: 4000
