annotations:
  truecharts.org/category: media
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
- alias: ''
  condition: redis.enabled
  import-values: []
  name: redis
  repository: oci://tccr.io/truecharts
  tags: []
  version: 14.0.5
deprecated: false
description: High performance self-hosted photo and video backup solution.
home: https://truecharts.org/charts/stable/immich
icon: https://truecharts.org/img/hotlink-ok/chart-icons/immich.webp
keywords:
- photos
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: immich
sources:
- https://github.com/immich-app/immich
- https://github.com/truecharts/charts/tree/master/charts/stable/immich
- https://hub.docker.com/r/altran1502/immich-machine-learning
- https://hub.docker.com/r/altran1502/immich-server
type: application
version: 2025.1.26
