image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/linuxserver/ngircd
  tag: latest
persistence:
  config:
    enabled: true
    mountPath: /config
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 6667
        targetPort: 6667
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
