humhub:
  admin:
    email: humhub@example.com
    login: admin
    password: test
  host: localhost:8080
  mailer:
    allow_self_sign_certs: false
    encrypt: ''
    hostname: ''
    password: ''
    port: 1025
    sys_address: noreply@example.com
    sys_name: HumHub
    type: smtp
    user: ''
  nginx:
    keep_alive_timeout: 65
    max_client_body_size: 10m
  proto: http
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/mriedmann/humhub-phponly
  tag: latest
mariadb:
  enabled: true
  includeCommon: true
  mariadbDatabase: humhub
  mariadbUsername: humhub
nginxImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/mriedmann/humhub-nginx
  tag: 1.15.4@sha256:afb417b4161a09ddaafdc2003f074b17099865be22d0547a76a731b213561344
persistence:
  assets:
    enabled: true
    mountPath: /var/www/localhost/htdocs/assets
    targetSelector:
      main:
        main:
          mountPath: /var/www/localhost/htdocs/assets
      nginx:
        nginx:
          mountPath: /var/www/localhost/htdocs/assets
  config:
    enabled: true
    mountPath: /var/www/localhost/htdocs/protected/config
  modules:
    enabled: true
    targetSelector:
      main:
        main:
          mountPath: /var/www/localhost/htdocs/protected/modules
      nginx:
        nginx:
          mountPath: /var/www/localhost/htdocs/protected/modules
  themes:
    enabled: true
    mountPath: /var/www/localhost/htdocs/themes
    targetSelector:
      main:
        main:
          mountPath: /var/www/localhost/htdocs/themes
      nginx:
        nginx:
          mountPath: /var/www/localhost/htdocs/themes
  uploads:
    enabled: true
    targetSelector:
      main:
        main:
          mountPath: /var/www/localhost/htdocs/uploads
      nginx:
        nginx:
          mountPath: /var/www/localhost/htdocs/uploads
portal:
  open:
    enabled: true
redis:
  enabled: true
  includeCommon: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  backend:
    enabled: true
    ports:
      backend:
        enabled: true
        port: 9000
        targetPort: 9000
        targetSelector: main
    targetSelector: main
    type: ClusterIP
  main:
    ports:
      main:
        port: 8080
        protocol: http
        targetPort: 80
        targetSelector: nginx
    targetSelector: nginx
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HUMHUB_ADMIN_EMAIL: '{{ .Values.humhub.admin.email }}'
            HUMHUB_ADMIN_LOGIN: '{{ .Values.humhub.admin.login }}'
            HUMHUB_ADMIN_PASSWORD: '{{ .Values.humhub.admin.password }}'
            HUMHUB_AUTO_INSTALL: true
            HUMHUB_CACHE_CLASS: yii\redis\Cache
            HUMHUB_CACHE_EXPIRE_TIME: 3600
            HUMHUB_DB_HOST:
              secretKeyRef:
                expandObjectName: false
                key: plainhost
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
            HUMHUB_DB_NAME: '{{ .Values.mariadb.mariadbDatabase }}'
            HUMHUB_DB_PASSWORD: '{{ .Values.mariadb.password }}'
            HUMHUB_DB_USER: '{{ .Values.mariadb.mariadbUsername }}'
            HUMHUB_HOST: '{{ .Values.humhub.host }}'
            HUMHUB_INTEGRITY_CHECK: true
            HUMHUB_MAILER_ALLOW_SELF_SIGNED_CERTS: '{{ .Values.humhub.mailer.allow_self_sign_certs
              }}'
            HUMHUB_MAILER_ENCRYPTION: '{{ .Values.humhub.mailer.encrypt }}'
            HUMHUB_MAILER_HOSTNAME: '{{ .Values.humhub.mailer.hostname }}'
            HUMHUB_MAILER_PASSWORD: '{{ .Values.humhub.mailer.password }}'
            HUMHUB_MAILER_PORT: '{{ .Values.humhub.mailer.port }}'
            HUMHUB_MAILER_SYSTEM_EMAIL_ADDRESS: '{{ .Values.humhub.mailer.sys_address
              }}'
            HUMHUB_MAILER_SYSTEM_EMAIL_NAME: '{{ .Values.humhub.mailer.sys_name }}'
            HUMHUB_MAILER_TRANSPORT_TYPE: '{{ .Values.humhub.mailer.type }}'
            HUMHUB_MAILER_USERNAME: '{{ .Values.humhub.mailer.user }}'
            HUMHUB_PROTO: '{{ .Values.humhub.proto }}'
            HUMHUB_QUEUE_CLASS: humhub\modules\queue\driver\Redis
            HUMHUB_REDIS_HOSTNAME:
              secretKeyRef:
                expandObjectName: false
                key: plainhost
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
            HUMHUB_REDIS_PASSWORD: '{{ .Values.redis.password }}'
            HUMHUB_REDIS_PORT: 6379
            WAIT_FOR_DB: true
          probes:
            liveness:
              command: /usr/local/bin/php-fpm-healthcheck
              enabled: true
              type: exec
            readiness:
              command: /usr/local/bin/php-fpm-healthcheck
              enabled: true
              type: exec
            startup:
              command: /usr/local/bin/php-fpm-healthcheck
              enabled: true
              type: exec
  nginx:
    enabled: true
    podSpec:
      containers:
        nginx:
          enabled: true
          env:
            HUMHUB_REVERSEPROXY_WHITELIST: 10.0.0.0/8;172.16.0.0/16;192.168.0.0/24
            NGINX_CLIENT_MAX_BODY_SIZE: '{{ .Values.humhub.nginx.max_client_body_size
              }}'
            NGINX_KEEPALIVE_TIMEOUT: '{{ .Values.humhub.nginx.keep_alive_timeout }}'
            NGINX_UPSTREAM: '{{ printf "%s-backend:9000" (include "tc.v1.common.lib.chart.names.fullname"
              $) }}'
          imageSelector: nginxImage
          primary: true
          probes:
            liveness:
              enabled: true
              path: /ping
              port: 80
              type: http
            readiness:
              enabled: true
              path: /ping
              port: 80
              type: http
            startup:
              enabled: true
              port: 80
              type: tcp
    type: Deployment
