annotations:
  truecharts.org/category: media
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: Drawio is free online diagram software.
home: https://truecharts.org/charts/stable/drawio
icon: https://truecharts.org/img/hotlink-ok/chart-icons/drawio.webp
keywords:
- drawio
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: drawio
sources:
- https://github.com/jgraph/drawio
- https://github.com/truecharts/charts/tree/master/charts/stable/drawio
- https://hub.docker.com/r/jgraph/drawio
type: application
version: 2025.1.26
