annotations:
  truecharts.org/category: utilities
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: Fluidd is a free and open-source Klipper web interface for managing your
  3d printer.
home: https://truecharts.org/charts/stable/fluidd
icon: https://truecharts.org/img/hotlink-ok/chart-icons/fluidd.webp
keywords:
- fluidd
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: fluidd
sources:
- https://ghcr.io/fluidd-core/fluidd
- https://github.com/fluidd-core/fluidd
- https://github.com/truecharts/charts/tree/master/charts/stable/fluidd
type: application
version: 2025.1.26
