image:
  pullPolicy: IfNotPresent
  repository: anirdev/slink
  tag: latest
ingress:
  main:
    required: true
persistence:
  database:
    enabled: true
    mountPath: /app/var/data
  images:
    enabled: true
    mountPath: /app/slink/images
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: http
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            IMAGE_MAX_SIZE: 15M
            ORIGIN: '{{ .Values.chartContext.appUrl }}'
            USER_APPROVAL_REQUIRED: true
