annotations:
  truecharts.org/category: office
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: An awesome, Online Office suite image suitable for home use.
home: https://truecharts.org/charts/stable/collabora
icon: https://truecharts.org/img/hotlink-ok/chart-icons/collabora.webp
keywords:
- office
- document
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: collabora
sources:
- https://github.com/CollaboraOnline/online
- https://github.com/truecharts/charts/tree/master/charts/stable/collabora
- https://hub.docker.com/r/collabora/code
type: application
version: 2025.1.26
