annotations:
  truecharts.org/category: Productivity
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: "HexChat is an IRC client based on XChat, but unlike XChat it\u2019s\
  \ completely free for both Windows and Unix-like systems. Since XChat is open source,\
  \ it\u2019s perfectly legal. For more info. HexChat was originally called XChat-WDK\
  \ which in turn was a successor of freakschat."
home: https://truecharts.org/charts/stable/hexchat
icon: https://truecharts.org/img/hotlink-ok/chart-icons/hexchat.webp
keywords:
- hexchat
- Productivity
- Tools-Utilities
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: hexchat
sources:
- https://github.com/binhex/documentation
- https://github.com/truecharts/charts/tree/master/charts/stable/hexchat
- https://hexchat.github.io/
- https://hub.docker.com/r/binhex/arch-hexchat
- https://registry.hub.docker.com/r/binhex/arch-hexchat/
type: application
version: 2025.1.26
