image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/cops
  tag: latest
persistence:
  books:
    enabled: true
    mountPath: /books
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10609
        protocol: http
        targetPort: 80
