annotations:
  truecharts.org/category: rss
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: Miniflux is a minimalist and opinionated feed reader.
home: https://truecharts.org/charts/stable/miniflux
icon: https://truecharts.org/img/hotlink-ok/chart-icons/miniflux.webp
keywords:
- miniflux
- rss
- news
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: miniflux
sources:
- https://github.com/miniflux/v2
- https://github.com/truecharts/charts/tree/master/charts/stable/miniflux
- https://hub.docker.com/r/miniflux/miniflux
type: application
version: 2025.1.26
