annotations:
  truecharts.org/category: download-tools
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: fast, easy, and free BitTorrent client.
home: https://truecharts.org/charts/stable/transmission
icon: https://truecharts.org/img/hotlink-ok/chart-icons/transmission.webp
keywords:
- transmission
- torrent
- usenet
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: transmission
sources:
- https://ghcr.io/onedr0p/transmission
- https://github.com/transmission/transmission
- https://github.com/truecharts/charts/tree/master/charts/stable/transmission
type: application
version: 2025.1.26
