annotations:
  truecharts.org/category: media
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: An FTP automation tool that periodically scans given host locations for
  new files.
home: https://truecharts.org/charts/stable/davos
icon: https://truecharts.org/img/hotlink-ok/chart-icons/davos.webp
keywords:
- davos
- ftp
- automation
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: davos
sources:
- https://ghcr.io/linuxserver/davos
- https://github.com/linuxserver/davos/
- https://github.com/linuxserver/docker-davos
- https://github.com/truecharts/charts/tree/master/charts/stable/davos
type: application
version: 2025.1.26
