annotations:
  truecharts.org/category: media
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: Airsonic is a Free and Open Source community driven media server
home: https://truecharts.org/charts/stable/airsonic-advanced
icon: https://truecharts.org/img/hotlink-ok/chart-icons/airsonic-advanced.webp
keywords:
- airsonic
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: airsonic-advanced
sources:
- https://github.com/airsonic/airsonic-advanced
- https://github.com/truecharts/charts/tree/master/charts/stable/airsonic-advanced
- https://hub.docker.com/r/airsonicadvanced/airsonic-advanced
type: application
version: 2025.1.26
