annotations:
  max_scale_version: 24.04.0
  min_scale_version: 23.10.0
  truecharts.org/category: operators
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: system
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 20.2.10
- alias: velero
  condition: ''
  import-values: []
  name: velero
  repository: oci://ghcr.io/vmware-tanzu/charts
  tags: []
  version: 5.4.1
deprecated: false
description: Velero is a kubernetes-native backup solution
home: https://truecharts.org/charts/system/velero
icon: https://truecharts.org/img/hotlink-ok/chart-icons/velero.png
keywords:
- velero
- backup
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: velero
sources:
- https://cert-manager.io/
- https://github.com/cert-manager
- https://github.com/truecharts/charts/tree/master/charts/system/velero
- https://github.com/truecharts/containers/tree/master/apps/alpine
type: application
version: 2025.1.26
