annotations:
  truecharts.org/category: utilities
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: CyberChef is a simple, intuitive web app for carrying out all manner
  of "cyber" operations within a web browser.
home: https://truecharts.org/charts/stable/cyberchef
icon: https://truecharts.org/img/hotlink-ok/chart-icons/cyberchef.webp
keywords:
- cyberchef
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: cyberchef
sources:
- https://github.com/truecharts/charts/tree/master/charts/stable/cyberchef
- https://hub.docker.com/r/mpepping/cyberchef
type: application
version: 2025.1.26
