annotations:
  truecharts.org/category: media
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: M3U Proxy for Plex DVR and Emby Live TV.
home: https://truecharts.org/charts/stable/xteve
icon: https://truecharts.org/img/hotlink-ok/chart-icons/xteve.webp
keywords:
- xteve
- iptv
- plex
- emby
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: xteve
sources:
- https://ghcr.io/k8s-at-home/xteve
- https://github.com/k8s-at-home/container-images
- https://github.com/truecharts/charts/tree/master/charts/stable/xteve
- https://github.com/xteve-project/xTeVe
type: application
version: 2025.1.26
