image:
  pullPolicy: IfNotPresent
  repository: coleifer/sqlite-web
  tag: latest
persistence:
  data:
    enabled: true
    mountPath: /data
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8080
        protocol: tcp
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SQLITE_DATABASE: db_name.db
