cnpg:
  main:
    database: vikunja
    enabled: true
    user: vikunja
frontendImage:
  pullPolicy: IfNotPresent
  repository: vikunja/frontend
  tag: 0.22.1@sha256:f0223d441997fe29c377d0b476dc4bb2fc091b44b9c24d76b1b88c213df520c5
image:
  pullPolicy: IfNotPresent
  repository: vikunja/api
  tag: latest
metrics:
  main:
    enabled: true
    prometheusRule:
      enabled: false
    type: servicemonitor
nginxImage:
  repository: nginx
  tag: 1.26.0@sha256:192e88a0053c178683ca139b9d9a2afb0ad986d171fae491949fe10970dd9da9
persistence:
  files:
    enabled: true
    mountPath: /app/vikunja/files
  vikunja-config:
    enabled: true
    objectName: config
    targetSelector:
      main:
        main:
          mountPath: /etc/vikunja/config.yaml
          subPath: config.yaml
    type: secret
  vikunja-nginx:
    enabled: true
    noMount: true
    objectName: nginx-config
    targetSelector:
      main:
        proxy:
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx-config
    type: configmap
portal:
  open:
    enabled: true
redis:
  enabled: true
  includeCommon: true
securityContext:
  container:
    capabilities:
      add:
      - NET_BIND_SERVICE
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10220
updated: true
vikunja:
  auth:
    local:
      enabled: true
    openid:
      enabled: false
      providers: []
      redirecturl: ''
  avatar:
    gravatarexpiration: 3600
  backgrounds:
    enabled: true
    providers:
      unsplash:
        accesstoken: ''
        applicationid: ''
        enabled: false
      upload:
        enabled: true
  cors:
    enabled: true
    maxage: 0
    origins: []
  defaultsettings:
    avatar_file_id: 0
    avatar_provider: initials
    default_list_id: 0
    discoverable_by_email: false
    discoverable_by_name: false
    email_reminders_enabled: false
    language: ''
    overdue_tasks_reminders_enabled: true
    overdue_tasks_reminders_time: '9:00'
    timezone: ''
    week_start: 0
  files:
    maxsize: 20MB
  legal:
    imprinturl: ''
    privacyurl: ''
  log:
    database: 'off'
    databaselevel: WARNING
    echo: 'off'
    enabled: true
    events: stdout
    eventslevel: INFO
    http: stdout
    level: INFO
    path: /app/vikunja/logs
    standard: stdout
  mailer:
    authtype: plain
    enabled: false
    forcessl: true
    fromemail: ''
    host: ''
    password: ''
    port: 587
    queuelength: 100
    queuetimeout: 30
    skiptlsverify: false
    username: ''
  migration:
    microsofttodo:
      clientid: ''
      clientsecret: ''
      enable: false
      redirecturl: ''
    todoist:
      clientid: ''
      clientsecret: ''
      enable: false
      redirecturl: ''
    trello:
      enable: false
      key: ''
      redirecturl: ''
  ratelimit:
    enabled: false
    kind: user
    limit: 100
    period: 60
  service:
    enablecaldav: true
    enableemailreminders: true
    enablelinksharing: true
    enableregistration: true
    enabletaskattachments: true
    enabletaskcomments: true
    enabletotp: true
    enableuserdeletion: true
    frontendurl: http://localhost:10220
    jwtttl: 259200
    jwtttllong: 2592000
    maxavatarsize: 1024
    maxitemsperpage: 50
    motd: Welcome to your new Vikunja instance
workload:
  main:
    podSpec:
      containers:
        frontend:
          enabled: true
          imageSelector: frontendImage
          probes:
            liveness:
              port: 80
              type: http
            readiness:
              port: 80
              type: http
            startup:
              port: 80
              type: http
        main:
          probes:
            liveness:
              path: /health
              port: 3456
              type: http
            readiness:
              path: /health
              port: 3456
              type: http
            startup:
              path: /health
              port: 3456
              type: http
        proxy:
          enabled: true
          imageSelector: nginxImage
          probes:
            liveness:
              port: '{{ .Values.service.main.ports.main.port }}'
              type: http
            readiness:
              port: '{{ .Values.service.main.ports.main.port }}'
              type: http
            startup:
              port: '{{ .Values.service.main.ports.main.port }}'
              type: http
