image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/linuxserver/pylon
  tag: latest
persistence:
  code:
    enabled: true
    mountPath: /code
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3131
        targetPort: 3131
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GITURL: ''
            PYPASS: ''
            PYUSER: ''
