annotations:
  truecharts.org/category: website
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
- alias: ''
  condition: mariadb.enabled
  import-values: []
  name: mariadb
  repository: oci://tccr.io/truecharts
  tags: []
  version: 14.0.10
deprecated: false
description: The WordPress rich content management system can utilize plugins, widgets,
  and themes.
home: https://truecharts.org/charts/stable/wordpress
icon: https://truecharts.org/img/hotlink-ok/chart-icons/wordpress.webp
keywords:
- wordpress
- cms
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: wordpress
sources:
- https://github.com/truecharts/charts/tree/master/charts/stable/wordpress
- https://hub.docker.com/r/bitnami/wordpress
- https://www.wordpress.org
type: application
version: 2025.1.26
