annotations:
  truecharts.org/category: home-automation
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: The Wyoming integration of piper
home: https://truecharts.org/charts/stable/wyoming-piper
icon: https://truecharts.org/img/hotlink-ok/chart-icons/wyoming-piper.webp
keywords:
- wyoming-piper
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: wyoming-piper
sources:
- https://github.com/home-assistant/addons/tree/master/piper
- https://github.com/truecharts/charts/tree/master/charts/stable/wyoming-piper
- https://hub.docker.com/r/rhasspy/wyoming-piper
type: application
version: 2025.1.26
