annotations:
  truecharts.org/category: Tools-Utilities
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: Webtop full desktop environments in officially supported flavors accessible
  via any modern web browser.
home: https://truecharts.org/charts/stable/webtop
icon: https://truecharts.org/img/hotlink-ok/chart-icons/webtop.webp
keywords:
- webtop
- Tools-Utilities
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: webtop
sources:
- https://fleet.linuxserver.io/image?name=linuxserver/webtop
- https://github.com/linuxserver/docker-webtop#readme
- https://github.com/linuxserver/gclient
- https://github.com/orgs/linuxserver/packages/container/package/webtop
- https://github.com/truecharts/charts/tree/master/charts/stable/webtop
type: application
version: 2025.1.26
