image:
  pullPolicy: IfNotPresent
  repository: registry
  tag: latest
persistence:
  datastoragepath:
    enabled: true
    mountPath: /var/lib/registry
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 5000
        protocol: tcp
        targetPort: 5000
