image:
  pullPolicy: IfNotPresent
  repository: pihole/pihole
  tag: latest
persistence:
  config:
    enabled: true
    mountPath: /etc/pihole
  dnsmasq:
    enabled: true
    mountPath: /etc/dnsmasq.d
pihole:
  dnsServers:
  - 9.9.9.9
  - 149.112.112.112
  webPassword: somepassword"
portal:
  open:
    enabled: true
securityContext:
  container:
    allowPrivilegeEscalation: true
    capabilities:
      add:
      - NET_ADMIN
      - SETFCAP
      - SETPCAP
      - KILL
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  dns:
    enabled: true
    ports:
      dns:
        enabled: true
        port: 53
        protocol: udp
        targetPort: 53
      dns-tcp:
        enabled: true
        port: '{{ .Values.service.dns.ports.dns.port }}'
        protocol: tcp
        targetPort: 53
  main:
    ports:
      main:
        port: 9089
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          envFrom:
          - configMapRef:
              name: pihole-env
          probes:
            liveness:
              path: /admin/index.php
              type: http
            readiness:
              path: /admin/index.php
              type: http
            startup:
              path: /admin/index.php
              type: http
