image:
  pullPolicy: IfNotPresent
  repository: housewrecker/gaps
  tag: latest
persistence:
  data:
    enabled: true
    mountPath: /usr/data
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
service:
  main:
    ports:
      main:
        port: 8484
        targetPort: 8484
workload:
  main:
    podSpec:
      containers:
        main:
          env: {}
