annotations:
  truecharts.org/category: social
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: A superlight rust written social server.
home: https://truecharts.org/charts/stable/vocechat-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/vocechat-server.webp
keywords:
- vocechat-server
- social
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: vocechat-server
sources:
- https://github.com/Privoce/vocechat-server-rust
- https://github.com/truecharts/charts/tree/master/charts/stable/vocechat-server
- https://hub.docker.com/r/privoce/vocechat-server
type: application
version: 2025.1.26
