affinity: {}
image:
  pullPolicy: IfNotPresent
  repository: mikenye/piaware
  tag: latest
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10092
        targetPort: 8080
