annotations:
  truecharts.org/category: media
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: This is the multi-platform Docker image for My Media for Alexa - https://www.mymediaalexa.com
  .
home: https://truecharts.org/charts/stable/mymediaforalexa
icon: https://truecharts.org/img/hotlink-ok/chart-icons/mymediaforalexa.webp
keywords:
- media
- alexa
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: mymediaforalexa
sources:
- https://github.com/truecharts/charts/tree/master/charts/stable/mymediaforalexa
- https://hub.docker.com/r/bizmodeller/mymediaforalexa
- https://www.mymediaalexa.com/home/docker#dockerhub
type: application
version: 2025.1.26
