image:
  pullPolicy: IfNotPresent
  repository: qmcgaw/stackedit
  tag: latest
persistence: {}
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8000
        protocol: tcp
        targetPort: 8000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ROOT_URL: /
