annotations:
  truecharts.org/category: media
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
- alias: ''
  condition: mariadb.enabled
  import-values: []
  name: mariadb
  repository: oci://tccr.io/truecharts
  tags: []
  version: 14.0.10
deprecated: false
description: "PhotoPrism\xAE is a server-based application for browsing, organizing\
  \ and sharing your personal photo collection"
home: https://truecharts.org/charts/stable/photoprism
icon: https://truecharts.org/img/hotlink-ok/chart-icons/photoprism.webp
keywords:
- photos
- photoprism
- pictures
- sharing
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: photoprism
sources:
- https://github.com/photoprism/photoprism
- https://github.com/truecharts/charts/tree/master/charts/stable/photoprism
- https://hub.docker.com/r/photoprism/photoprism
type: application
version: 2025.1.26
