image:
  pullPolicy: IfNotPresent
  repository: photoprism/photoprism
  tag: latest
mariadb:
  enabled: true
  mariadbDatabase: photoprism
  mariadbUsername: photoprism
persistence:
  import:
    enabled: true
    mountPath: /photoprism/import
  originals:
    enabled: true
    mountPath: /photoprism/originals
  photoprismtemp:
    enabled: true
    mountPath: /photoprism_temp
    type: emptyDir
  storage:
    enabled: true
    mountPath: /assets
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
service:
  main:
    ports:
      main:
        port: 2342
        targetPort: 2342
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HOME: /photoprism
            PHOTOPRISM_ADMIN_PASSWORD: please-change
            PHOTOPRISM_CACHE_PATH: /assets/cache
            PHOTOPRISM_CONFIG_PATH: /assets/config
            PHOTOPRISM_DATABASE_DRIVER: mysql
            PHOTOPRISM_DATABASE_NAME: photoprism
            PHOTOPRISM_DATABASE_PASSWORD:
              secretKeyRef:
                expandObjectName: false
                key: mariadb-password
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
            PHOTOPRISM_DATABASE_SERVER:
              secretKeyRef:
                expandObjectName: false
                key: plainporthost
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
            PHOTOPRISM_DATABASE_USER: photoprism
            PHOTOPRISM_GID: '{{ .Values.securityContext.container.runAsGroup }}'
            PHOTOPRISM_IMPORT_PATH: /photoprism/import
            PHOTOPRISM_ORIGINALS_PATH: /photoprism/originals
            PHOTOPRISM_PUBLIC: false
            PHOTOPRISM_SIDECAR_PATH: /assets/sidecar
            PHOTOPRISM_STORAGE_PATH: /assets/storage
            PHOTOPRISM_TEMP_PATH: /photoprism_temp
            PHOTOPRISM_UID: '{{ .Values.securityContext.container.runAsUser }}'
            PHOTOPRISM_UMASK: '{{ .Values.securityContext.container.UMASK }}'
            PROTOPRISM_BACKUP_PATH: /assets/backup
