image:
  pullPolicy: IfNotPresent
  repository: mongoclient/mongoclient
  tag: latest
persistence:
  appdata:
    enabled: true
    mountPath: /data/db
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            MONGO_URL: ''
