annotations:
  truecharts.org/category: incubator
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
- alias: ''
  condition: mariadb.enabled
  import-values: []
  name: mariadb
  repository: oci://tccr.io/truecharts
  tags: []
  version: 14.0.10
deprecated: false
description: Fleet provides an online web interface which displays a set of maintained
  images from one or more owned repositories.
home: https://truecharts.org/charts/stable/fleet
icon: https://truecharts.org/img/hotlink-ok/chart-icons/fleet.webp
keywords:
- fleet
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: fleet
sources:
- https://ghcr.io/linuxserver/fleet
- https://github.com/truecharts/charts/tree/master/charts/stable/fleet
type: application
version: 2025.1.26
