image:
  pullPolicy: IfNotPresent
  repository: simonjenny/fastcom-mqtt
  tag: latest
persistence: {}
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            MQTT_DOWN: ''
            MQTT_SERVER: ''
            MQTT_UP: ''
            SLEEP: '3600'
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
