annotations:
  truecharts.org/category: Network-Messenger
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: Convos is the simplest way to use IRC and it is always online
home: https://truecharts.org/charts/stable/convos
icon: https://truecharts.org/img/hotlink-ok/chart-icons/convos.webp
keywords:
- convos
- Network-Messenger
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: convos
sources:
- https://convos.chat/
- https://github.com/truecharts/charts/tree/master/charts/stable/convos
- https://hub.docker.com/r/convos/convos
type: application
version: 2025.1.26
