image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/sethforprivacy/simple-monerod
  tag: latest
monero:
  enablednsblocklist: true
  noigd: true
  pruneblockchain: true
  publicnode: true
  rpcbindip: 0.0.0.0
  rpcbindport: '18089'
persistence:
  blockchainstorage:
    enabled: true
    mountPath: /home/monero/.bitmonero
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 18080
        protocol: tcp
        targetPort: 18080
  rpc:
    enabled: true
    ports:
      rpc:
        enabled: true
        port: 18089
        protocol: tcp
        targetPort: 18089
