image:
  pullPolicy: IfNotPresent
  repository: guacamole/guacd
  tag: latest
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 1000
    runAsUser: 1000
service:
  main:
    ports:
      main:
        port: 4822
        targetPort: 4822
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
