image:
  pullPolicy: IfNotPresent
  repository: rossimo/retrobot
  tag: latest
persistence:
  data:
    enabled: true
    mountPath: /retrobot/data
portal:
  open:
    enabled: false
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DISCORD_TOKEN: ''
            MAX_WORKERS: -1
            MAX_WORKERS_PER_GAME: 3
            RECORDING_FRAMERATE: 30
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
