annotations:
  truecharts.org/category: GameServers
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: A custom SteamCMD chart that runs Palworld.
home: https://truecharts.org/charts/stable/palworld
icon: https://truecharts.org/img/hotlink-ok/chart-icons/palworld.webp
keywords:
- palworld
- GameServers
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: palworld
sources:
- https://ghcr.io/ich777/steamcmd
- https://github.com/ich777/docker-steamcmd-server/tree/palworld
- https://github.com/truecharts/charts/tree/master/charts/stable/palworld
- https://hub.docker.com/r/outdead/rcon
type: application
version: 2025.1.26
