annotations:
  truecharts.org/category: network
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: ZeroTier is a smart programmable Ethernet switch for planet Earth
home: https://truecharts.org/charts/stable/zerotier
icon: https://truecharts.org/img/hotlink-ok/chart-icons/zerotier.webp
keywords:
- zerotier
- network
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: zerotier
sources:
- https://github.com/truecharts/charts/tree/master/charts/stable/zerotier
- https://hub.docker.com/r/zerotier/zerotier
type: application
version: 2025.1.26
