image:
  pullPolicy: IfNotPresent
  repository: docker.io/zerotier/zerotier
  tag: latest
persistence:
  config:
    enabled: true
    mountPath: /var/lib/zerotier-one
  tun:
    enabled: true
    hostPath: /dev/net/tun
    hostPathType: ''
    mountPath: /dev/net/tun
    readOnly: false
    type: hostPath
portal:
  open:
    enabled: false
securityContext:
  container:
    capabilities:
      add:
      - NET_ADMIN
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10190
        protocol: udp
        targetPort: 9993
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ZEROTIER_API_SECRET: ''
            ZEROTIER_IDENTITY_PUBLIC: ''
            ZEROTIER_IDENTITY_SECRET: ''
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
