annotations:
  truecharts.org/category: Downloaders
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: This tool will help manage tedious tasks in qBittorrent and automate
  them. Tag, categorize, remove orphaned data, remove unregistered torrents and much
  much more.
home: https://truecharts.org/charts/stable/qbitmanage
icon: https://truecharts.org/img/hotlink-ok/chart-icons/qbitmanage.webp
keywords:
- qbitmanage
- Downloaders
- MediaApp-Other
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: qbitmanage
sources:
- https://github.com/StuffAnThings/qbit_manage/wiki/Docker-Installation
- https://github.com/truecharts/charts/tree/master/charts/stable/qbitmanage
- https://hub.docker.com/r/bobokun/qbit_manage
type: application
version: 2025.1.26
