image:
  pullPolicy: IfNotPresent
  repository: biospheere/promcord
  tag: latest
metrics:
  main:
    enabled: true
    endpoints:
    - path: /metrics
      port: main
    prometheusRule:
      enabled: false
    type: servicemonitor
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
service:
  main:
    ports:
      main:
        enabled: true
        port: 8080
        type: ClusterIP
