image:
  pullPolicy: IfNotPresent
  repository: xtrendence/cryptofolio
  tag: latest
persistence:
  data:
    enabled: true
    mountPath: /var/www/html/api/data
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10007
        protocol: http
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env: {}
          probes:
            liveness:
              path: /
              type: http
            readiness:
              path: /
              type: http
            startup:
              path: /
              type: http
