image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/geek-cookbook/nzbget
  tag: latest
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 10057
        targetPort: 6789
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
