image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/tzahi12345/youtubedl-material
  tag: latest
mongodb:
  enabled: true
  mongodbDatabase: ytdl_material
  mongodbUsername: ytdl_material
persistence:
  appdata:
    enabled: true
    mountPath: /app/appdata
  audio:
    enabled: true
    mountPath: /app/audio
  subscriptions:
    enabled: true
    mountPath: /app/subscriptions
  users:
    enabled: true
    mountPath: /app/users
  video:
    enabled: true
    mountPath: /app/video
portal:
  open:
    enabled: true
security:
  PUID: 1000
securityContext:
  container:
    fsGroup: 1000
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10253
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ALLOW_CONFIG_MUTATIONS: true
            write_ytdl_config: true
            ytdl_allow_advanced_download: false
            ytdl_allow_playlist_categorization: true
            ytdl_allow_quality_select: true
            ytdl_allow_subscriptions: true
            ytdl_allow_theme_change: true
            ytdl_api_key: ''
            ytdl_custom_args: ''
            ytdl_custom_downloading_agent: ''
            ytdl_default_downloader: yt-dlp
            ytdl_default_file_output: ''
            ytdl_default_theme: default
            ytdl_download_only_mode: false
            ytdl_download_rate_limit: ''
            ytdl_enable_downloads_manager: true
            ytdl_file_manager_enabled: true
            ytdl_generate_nfo_files: false
            ytdl_include_metadata: true
            ytdl_include_thumbnail: true
            ytdl_jwt_expiration: 86400
            ytdl_logger_level: debug
            ytdl_max_concurrent_downloads: 5
            ytdl_mongodb_connection_string:
              secretKeyRef:
                expandObjectName: false
                key: url
                name: '{{ printf "%s-%s" .Release.Name "mongodbcreds" }}'
            ytdl_multi_user_mode: false
            ytdl_port: '{{ .Values.service.main.ports.main.port }}'
            ytdl_subscriptions_check_interval: 86400
            ytdl_subscriptions_redownload_fresh_uploads: false
            ytdl_title_top: YoutubeDL-Material
            ytdl_twitch_api_key: ''
            ytdl_twitch_auto_download_chat: false
            ytdl_url: ''
            ytdl_use_api_key: false
            ytdl_use_cookies: false
            ytdl_use_default_downloading_agent: true
            ytdl_use_local_db: false
            ytdl_use_sponsorblock_api: false
            ytdl_use_twitch_api: false
            ytdl_use_youtubedl_archive: false
            ytdl_youtube_api_key: ''
