image:
  pullPolicy: IfNotPresent
  repository: bgameiro/arch-cern-root
  tag: latest
persistence:
  appdata:
    enabled: true
    mountPath: /appdata
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 9999
        protocol: tcp
        targetPort: 8888
