image:
  pullPolicy: IfNotPresent
  repository: fjudith/pwm
  tag: latest
persistence:
  appdata:
    enabled: true
    mountPath: /usr/share/pwm
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8282
        protocol: tcp
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PWM_APPLICATIONFLAGS: NoFileLock
