beImage:
  pullPolicy: IfNotPresent
  repository: portainer/portainer-ee
  tag: 2.20.3@sha256:afadde3ae572f2346d0e04965171f6f1d2f1d06023796053c327e183c75d6cc6
image:
  pullPolicy: IfNotPresent
  repository: portainer/portainer-ce
  tag: latest
persistence:
  cache:
    enabled: true
    mountPath: /.cache
    type: emptyDir
  data:
    enabled: true
    mountPath: /data
portainer:
  edge_compute: false
  hide_labels: null
  logo: ''
  snapshot_interval: 5m
portal:
  open:
    enabled: true
rbac:
  main:
    clusterWide: true
    enabled: true
    primary: true
    rules:
    - apiGroups:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
service:
  edge:
    enabled: true
    ports:
      edge:
        enabled: true
        port: 10401
        targetPort: 10401
  main:
    ports:
      main:
        port: 10400
        protocol: https
        targetPort: 9443
serviceAccount:
  main:
    enabled: true
    primary: true
updated: true
workload:
  main:
    podSpec:
      automountServiceAccountToken: true
      containers:
        main:
          imageSelector: image
          probes:
            liveness:
              port: 9443
              type: https
            readiness:
              port: 9443
              type: https
            startup:
              port: 9443
              type: https
