image:
  pullPolicy: IfNotPresent
  repository: leonismoe/ariang
  tag: latest
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 10276
        protocol: http
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          env: {}
          probes:
            liveness:
              path: /
              type: http
            readiness:
              path: /
              type: http
            startup:
              path: /
              type: http
