annotations:
  truecharts.org/category: incubator
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: HedgeDoc lets you create real-time collaborative markdown notes.
home: https://truecharts.org/charts/stable/hedgedoc
icon: https://truecharts.org/img/hotlink-ok/chart-icons/hedgedoc.webp
keywords:
- hedgedoc
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: hedgedoc
sources:
- https://github.com/truecharts/charts/tree/master/charts/stable/hedgedoc
- https://quay.io/hedgedoc/hedgedoc
type: application
version: 2025.1.26
