image:
  pullPolicy: IfNotPresent
  repository: crazyq/pt_helper
  tag: latest
persistence:
  data:
    enabled: true
    mountPath: /data
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8192
        protocol: tcp
        targetPort: 8192
