image:
  pullPolicy: IfNotPresent
  repository: fletchto99/hexo-dev-blog
  tag: latest
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10306
        protocol: http
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HEXO_PLUGINS: ''
