annotations:
  truecharts.org/category: media
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: Emby Server is a home media server
home: https://truecharts.org/charts/stable/emby
icon: https://truecharts.org/img/hotlink-ok/chart-icons/emby.webp
keywords:
- jellyfin
- plex
- emby
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: emby
sources:
- https://ghcr.io/geek-cookbook/emby
- https://github.com/linuxserver/docker-emby.git
- https://github.com/truecharts/charts/tree/master/charts/stable/emby
type: application
version: 2025.1.26
