image:
  pullPolicy: IfNotPresent
  repository: n1try/mininote
  tag: latest
persistence:
  data:
    enabled: true
    mountPath: /app/data
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
