image:
  pullPolicy: IfNotPresent
  repository: whyour/qinglong
  tag: latest
persistence:
  data:
    enabled: true
    mountPath: /ql/data
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10176
        targetPort: 5700
