auth:
  enabled: false
configmap:
  config:
    data:
      mosquitto.conf: 'listener {{ .Values.service.main.ports.main.targetPort }}

        {{- if .Values.websockets.enabled }}

        listener {{ .Values.service.websockets.ports.websockets.targetPort }}

        protocol websockets

        {{- end }}

        {{- if .Values.auth.enabled }}

        allow_anonymous false

        {{- else }}

        allow_anonymous true

        {{- end }}

        {{- if .Values.persistence.data.enabled }}

        persistence true

        persistence_location {{ .Values.persistence.data.mountPath }}

        autosave_interval 1800

        {{- end }}

        {{- if .Values.persistence.configinc.enabled }}

        include_dir {{ .Values.persistence.configinc.mountPath }}

        {{- end }}

        '
    enabled: true
image:
  pullPolicy: IfNotPresent
  repository: eclipse-mosquitto
  tag: latest
ingress:
  websockets:
    enabled: false
    targetSelector:
      websockets: websockets
persistence:
  configinc:
    enabled: true
    mountPath: /mosquitto/configinc
  data:
    enabled: true
    mountPath: /mosquitto/data
  mosquitto-config:
    enabled: true
    mountPath: /mosquitto/config/mosquitto.conf
    objectName: config
    subPath: mosquitto.conf
    type: configmap
portal:
  open:
    enabled: false
service:
  main:
    ports:
      main:
        port: 1883
        targetPort: 1883
  websockets:
    enabled: true
    ports:
      websockets:
        enabled: true
        port: 9001
        targetPort: 9001
websockets:
  enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: true
              port: 1883
              type: tcp
            readiness:
              enabled: true
              port: 1883
              type: tcp
            startup:
              enabled: true
              port: 1883
              type: tcp
