authentik:
  credentials:
    bootstrapToken: ''
    email: my-mail@example.com
    password: my-password
  email:
    from: ''
    host: ''
    password: null
    port: 587
    timeout: 10
    useSSL: false
    useTLS: true
    username: null
  errorReporting:
    enabled: false
    environment: customer
    sendPII: false
    sentryDSN: ''
  general:
    allowUserChangeEmail: true
    allowUserChangeName: true
    allowUserChangeUsername: true
    avatars:
    - gravatar
    - initials
    disableStartupAnalytics: true
    disableUpdateCheck: false
    footerLinks:
    - href: https://goauthentik.io
      name: Authentik
    gdprCompliance: true
    impersonation: true
    overwriteDefaultBlueprints: false
    tokenLength: 128
  geoip:
    accountID: ''
    editionID: GeoLite2-City
    enabled: false
    frequency: 8
    licenseKey: ''
    wipeBuiltInDb: false
  ldap:
    taskTimeoutHours: 2
    tlsCiphers: 'null'
  logging:
    logLevel: info
  outposts:
    ldap:
      enabled: false
      token: ''
    proxy:
      enabled: false
      token: ''
    radius:
      enabled: false
      token: ''
cnpg:
  main:
    database: authentik
    enabled: true
    user: authentik
geoipImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/maxmind/geoipupdate
  tag: v7.0.1@sha256:80c57598a9ff552953e499cefc589cfe7b563d64262742ea42f2014251b557b0
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/goauthentik/server
  tag: latest
ingress:
  main:
    required: true
ldapImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/goauthentik/ldap
  tag: 2024.4.2@sha256:7f317da9b736dec3e53b71b7face1787d4f15aee00e80d003e5ff3b2d49ee382
metrics:
  ldapmetrics:
    enabled: true
    endpoints:
    - path: /metrics
      port: '{{ .Values.service.ldapmetrics.ports.ldapmetrics.port }}'
    prometheusRule:
      enabled: false
    type: servicemonitor
  proxymetrics:
    enabled: true
    endpoints:
    - path: /metrics
      port: '{{ .Values.service.proxymetrics.ports.proxymetrics.port }}'
    prometheusRule:
      enabled: false
    type: servicemonitor
  radiusmetrics:
    enabled: true
    endpoints:
    - path: /metrics
      port: '{{ .Values.service.radiusmetrics.ports.radiusmetrics.port }}'
    prometheusRule:
      enabled: false
    type: servicemonitor
  servermetrics:
    enabled: true
    endpoints:
    - path: /metrics
      port: '{{ .Values.service.servermetrics.ports.servermetrics.port }}'
    prometheusRule:
      enabled: false
    type: servicemonitor
persistence:
  blueprints:
    enabled: true
    targetSelector:
      worker:
        worker:
          mountPath: /blueprints/custom
  certs:
    enabled: true
    mountPath: /certs
    targetSelector:
      worker:
        worker:
          mountPath: /certs
  geoip:
    enabled: true
    targetSelector:
      geoip:
        geoip:
          mountPath: /usr/share/GeoIP
      main:
        main:
          mountPath: /geoip
      worker:
        worker:
          mountPath: /geoip
  media:
    enabled: true
    targetSelector:
      main:
        main:
          mountPath: /media
      worker:
        worker:
          mountPath: /media
  templates:
    enabled: true
    targetSelector:
      main:
        main:
          mountPath: /templates
      worker:
        worker:
          mountPath: /templates
portal:
  open:
    enabled: true
proxyImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/goauthentik/proxy
  tag: 2024.4.2@sha256:eac911ae10a2d5bb04897ab6a46302e585b8d0bcda145c4bd5d665bdfcf86e86
radiusImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/goauthentik/radius
  tag: 2024.4.2@sha256:41032d99fd47ff138198f1296b0c69dc9cfae14414cf379ac89943c34773658b
redis:
  enabled: true
  includeCommon: true
service:
  http:
    enabled: true
    ports:
      http:
        enabled: true
        port: 10230
        protocol: http
    type: ClusterIP
  ldap:
    enabled: true
    ports:
      ldap:
        enabled: true
        port: 389
        targetSelector: ldap
    targetSelector: ldap
  ldapmetrics:
    enabled: true
    ports:
      ldapmetrics:
        enabled: true
        port: 10233
        protocol: http
        targetSelector: ldap
    targetSelector: ldap
    type: ClusterIP
  ldaps:
    enabled: true
    ports:
      ldaps:
        enabled: true
        port: 636
        targetSelector: ldap
    targetSelector: ldap
  main:
    ports:
      main:
        port: 10229
        protocol: https
  proxy:
    enabled: true
    ports:
      http:
        enabled: true
        port: 10227
        protocol: http
        targetSelector: proxy
      https:
        enabled: true
        port: 10228
        protocol: https
        targetSelector: proxy
    targetSelector: proxy
  proxymetrics:
    enabled: true
    ports:
      proxymetrics:
        enabled: true
        port: 10234
        protocol: http
        targetSelector: proxy
    targetSelector: proxy
    type: ClusterIP
  radius:
    enabled: true
    ports:
      radius:
        enabled: true
        port: 1812
        protocol: udp
        targetSelector: radius
    targetSelector: radius
  radiusmetrics:
    enabled: true
    ports:
      radiusmetrics:
        enabled: true
        port: 10232
        protocol: http
        targetSelector: radius
    targetSelector: radius
    type: ClusterIP
  servermetrics:
    enabled: true
    ports:
      servermetrics:
        enabled: true
        port: 10231
        protocol: http
    type: ClusterIP
updated: true
workload:
  geoip:
    enabled: true
    podSpec:
      containers:
        geoip:
          enabled: true
          envFrom:
          - configMapRef:
              name: geoip
          - secretRef:
              name: geoip
          imageSelector: geoipImage
          primary: true
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          securityContext:
            capabilities:
              disableS6Caps: true
            runAsGroup: 0
            runAsUser: 0
    type: Deployment
  ldap:
    enabled: true
    podSpec:
      containers:
        ldap:
          enabled: true
          envFrom:
          - configMapRef:
              name: ldap
          - secretRef:
              name: ldap
          imageSelector: ldapImage
          primary: true
          probes:
            liveness:
              command:
              - /ldap
              - healthcheck
              enabled: true
              type: exec
            readiness:
              command:
              - /ldap
              - healthcheck
              enabled: true
              type: exec
            startup:
              command:
              - /ldap
              - healthcheck
              enabled: true
              type: exec
          securityContext:
            runAsGroup: 1000
            runAsUser: 1000
    type: Deployment
  main:
    enabled: true
    podSpec:
      containers:
        main:
          args:
          - server
          enabled: true
          envFrom:
          - configMapRef:
              name: server
          - secretRef:
              name: server-worker
          - configMapRef:
              name: server-worker
          imageSelector: image
          primary: true
          probes:
            liveness:
              command:
              - /lifecycle/ak
              - healthcheck
              enabled: true
              type: exec
            readiness:
              command:
              - /lifecycle/ak
              - healthcheck
              enabled: true
              type: exec
            startup:
              command:
              - /lifecycle/ak
              - healthcheck
              enabled: true
              type: exec
          securityContext:
            runAsGroup: 1000
            runAsUser: 1000
    type: Deployment
  proxy:
    enabled: true
    podSpec:
      containers:
        proxy:
          enabled: true
          envFrom:
          - configMapRef:
              name: proxy
          - secretRef:
              name: proxy
          imageSelector: proxyImage
          primary: true
          probes:
            liveness:
              command:
              - /proxy
              - healthcheck
              enabled: true
              type: exec
            readiness:
              command:
              - /proxy
              - healthcheck
              enabled: true
              type: exec
            startup:
              command:
              - /proxy
              - healthcheck
              enabled: true
              type: exec
          securityContext:
            runAsGroup: 1000
            runAsUser: 1000
    type: Deployment
  radius:
    enabled: true
    podSpec:
      containers:
        radius:
          enabled: true
          envFrom:
          - configMapRef:
              name: radius
          - secretRef:
              name: radius
          imageSelector: radiusImage
          primary: true
          probes:
            liveness:
              command:
              - /radius
              - healthcheck
              enabled: true
              type: exec
            readiness:
              command:
              - /radius
              - healthcheck
              enabled: true
              type: exec
            startup:
              command:
              - /radius
              - healthcheck
              enabled: true
              type: exec
          securityContext:
            runAsGroup: 1000
            runAsUser: 1000
    type: Deployment
  worker:
    enabled: true
    podSpec:
      containers:
        worker:
          args:
          - worker
          enabled: true
          envFrom:
          - secretRef:
              name: server-worker
          - configMapRef:
              name: server-worker
          imageSelector: image
          primary: true
          probes:
            liveness:
              command:
              - /lifecycle/ak
              - healthcheck
              enabled: true
              type: exec
            readiness:
              command:
              - /lifecycle/ak
              - healthcheck
              enabled: true
              type: exec
            startup:
              command:
              - /lifecycle/ak
              - healthcheck
              enabled: true
              type: exec
          securityContext:
            runAsGroup: 1000
            runAsUser: 1000
    type: Deployment
