annotations:
  truecharts.org/category: GameServers
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: This Chart will download and install a StarMade Dedicated Server. It
  will also install a basic server.cfg at the first startup.
home: https://truecharts.org/charts/stable/starmade
icon: https://truecharts.org/img/hotlink-ok/chart-icons/starmade.webp
keywords:
- starmade
- GameServers
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: starmade
sources:
- https://github.com/truecharts/charts/tree/master/charts/stable/starmade
- https://hub.docker.com/r/ich777/starmade-server
- https://www.star-made.org/
type: application
version: 2025.1.26
