image:
  pullPolicy: IfNotPresent
  repository: juchong/shapeshifter-docker
  tag: latest
persistence:
  config:
    enabled: true
    mountPath: /state
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 2222
        protocol: tcp
        targetPort: 2222
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ARGS: -transparent -server -state state -orport 127.0.0.1:3333 -transports
              obfs4 -bindaddr obfs4-0.0.0.0:2222 -logLevel DEBUG -enableLogging
