image:
  pullPolicy: IfNotPresent
  repository: ronnieroller/media-roller
  tag: latest
persistence:
  download:
    enabled: true
    mountPath: /download
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
