annotations:
  truecharts.org/category: media
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: A Helm chart for Kubernetes
home: https://truecharts.org/charts/stable/filezilla
icon: https://truecharts.org/img/hotlink-ok/chart-icons/filezilla.webp
keywords:
- filezilla
- ftp
- sftp
- ftps
- client
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: filezilla
sources:
- https://filezilla-project.org/
- https://ghcr.io/linuxserver/filezilla
- https://github.com/linuxserver/docker-filezilla
- https://github.com/truecharts/charts/tree/master/charts/stable/filezilla
type: application
version: 2025.1.26
