image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/linuxserver/filezilla
  tag: latest
persistence:
  config:
    enabled: true
    mountPath: /config
  varrun:
    enabled: false
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10035
        protocol: http
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          securityContext: null
