annotations:
  truecharts.org/category: incubator
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: Endlessh is an SSH tarpit that very slowly sends an endless, random SSH
  banner.
home: https://truecharts.org/charts/stable/endlessh
icon: https://truecharts.org/img/hotlink-ok/chart-icons/endlessh.webp
keywords:
- endlessh
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: endlessh
sources:
- https://ghcr.io/linuxserver/endlessh
- https://github.com/truecharts/charts/tree/master/charts/stable/endlessh
type: application
version: 2025.1.26
