image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/linuxserver/endlessh
  tag: latest
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: false
securityContext:
  container:
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10128
        protocol: tcp
        targetPort: 2222
workload:
  main:
    podSpec:
      containers:
        main:
          env: {}
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
