annotations:
  truecharts.org/category: AI
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: Open-source ChatGPT experience for LLMs, embedders, and vector databases.
home: https://truecharts.org/charts/stable/anything-llm
icon: https://truecharts.org/img/hotlink-ok/chart-icons/anything-llm.webp
keywords:
- anything-llm
- ai
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: anything-llm
sources:
- https://ghcr.io/mintplex-labs/anything-llm
- https://github.com/Mintplex-Labs/anything-llm
- https://github.com/truecharts/charts/tree/master/charts/stable/anything-llm
type: application
version: 2025.1.26
