image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/diamkil/socials
  tag: latest
persistence:
  socials:
    enabled: true
    mountPath: /app/people
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 7574
        protocol: tcp
        targetPort: 7574
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            LOG_LEVEL: info
