cnpg:
  main:
    database: babybuddy
    enabled: true
    user: babybuddy
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/linuxserver/babybuddy
  tag: latest
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10069
        protocol: http
        targetPort: 8000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            CSRF_TRUSTED_ORIGINS: ''
            DB_ENGINE: django.db.backends.postgresql
            DB_HOST:
              secretKeyRef:
                key: host
                name: cnpg-main-urls
            DB_NAME: '{{ .Values.cnpg.main.database }}'
            DB_PASSWORD:
              secretKeyRef:
                key: password
                name: cnpg-main-user
            DB_PORT: '5432'
            DB_USER: '{{ .Values.cnpg.main.user }}'
