image:
  pullPolicy: IfNotPresent
  repository: joch/s3backup
  tag: latest
persistence: {}
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ACCESS_KEY: Your AWS Access key
            CRON_SCHEDULE: 0 * * * *
            S3CMDPARAMS: ''
            S3PATH: s3://mybucket/
            SECRET_KEY: Your AWS Access secret
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
