image:
  pullPolicy: IfNotPresent
  repository: ninthwalker/slack-invite
  tag: latest
persistence: {}
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 7879
        protocol: tcp
        targetPort: 7879
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            COMMUNITY_NAME: myslackteam
            SLACK_TOKEN: Enter YOur slack token here
            SLACK_URL: myslackteam.slack.com
