image:
  pullPolicy: IfNotPresent
  repository: openspeedtest/latest
  tag: latest
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10256
        protocol: http
        targetPort: 3000
