annotations:
  truecharts.org/category: media
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: Python script to update metadata and automatically build collections.
home: https://truecharts.org/charts/stable/kometa
icon: https://truecharts.org/img/hotlink-ok/chart-icons/kometa.webp
keywords:
- kometa
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: kometa
sources:
- https://github.com/kometa-team/kometa
- https://github.com/truecharts/charts/tree/master/charts/stable/kometa
- https://hub.docker.com/r/kometateam/kometa
type: application
version: 2025.1.26
