image:
  pullPolicy: IfNotPresent
  repository: lastelement21/emby-sync
  tag: latest
persistence: {}
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 5000
        protocol: tcp
        targetPort: 5000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DEFAULT_ROOM: ''
            EMBY_SERVER: ''
            SECRET_KEY: ''
