image:
  pullPolicy: IfNotPresent
  repository: cloudflare/cloudflared
  tag: latest
portal:
  open:
    enabled: false
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          args:
          - tunnel
          - --no-autoupdate
          - run
          env:
            TUNNEL_TOKEN: ''
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
