annotations:
  truecharts.org/category: media
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: TinyMediaManager is a full featured media manager to organize and clean
  up your media library.
home: https://truecharts.org/charts/stable/tinymediamanager
icon: https://truecharts.org/img/hotlink-ok/chart-icons/tinymediamanager.webp
keywords:
- tiny
- media
- manager
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: tinymediamanager
sources:
- https://github.com/truecharts/charts/tree/master/charts/stable/tinymediamanager
- https://gitlab.com/tinyMediaManager/tinyMediaManager
- https://hub.docker.com/r/tinymediamanager/tinymediamanager
type: application
version: 2025.1.26
