image:
  pullPolicy: IfNotPresent
  repository: sinusbot/docker
  tag: latest
persistence:
  data:
    enabled: true
    mountPath: /opt/sinusbot/data
  scriptspath:
    enabled: true
    mountPath: /opt/sinusbot/scripts
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8087
        protocol: tcp
        targetPort: 8087
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            OVERRIDE_PASSWORD: foobar
