image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/wanjohiryan/qwantify
  tag: latest
persistence:
  games:
    enabled: true
    mountPath: /games
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10603
        protocol: http
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            APPFILE: /game.exe
            APPPATH: /games
