annotations:
  truecharts.org/category: media
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: Self hosted web app for shortening urls (URL shortener)
home: https://truecharts.org/charts/stable/shorturl
icon: https://truecharts.org/img/hotlink-ok/chart-icons/shorturl.webp
keywords:
- url
- shortener
- shorten
- shorturl
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: shorturl
sources:
- https://ghcr.io/nicholaswilde/shorturl
- https://github.com/nicholaswilde/docker-shorturl
- https://github.com/prologic/shorturl
- https://github.com/truecharts/charts/tree/master/charts/stable/shorturl
type: application
version: 2025.1.26
