annotations:
  truecharts.org/category: Productivity
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: CadQuery is an intuitive, easy-to-use Python module for building parametric
  3D CAD models. Using CadQuery, you can write short, simple scripts that produce
  high quality CAD models. It is easy to make many different objects using a single
  script that can be customized.
home: https://truecharts.org/charts/stable/cadquery-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/cadquery-server.webp
keywords:
- cadquery-server
- Productivity
- Tools-Utilities
- Other
- Network-Other
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: cadquery-server
sources:
- https://github.com/roipoussiere/cadquery
- https://github.com/truecharts/charts/tree/master/charts/stable/cadquery-server
- https://hub.docker.com/r/cadquery/cadquery-server
type: application
version: 2025.1.26
