image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/nicholaswilde/novnc
  tag: latest
persistence:
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 6080
        targetPort: 6080
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            REMOTE_HOST: localhost
            REMOTE_PORT: '5900'
