image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/linuxserver/quassel-web
  tag: latest
persistence:
  config:
    enabled: true
    mountPath: /config
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 64080
        targetPort: 64080
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            QUASSEL_CORE: 0.0.0.0
            QUASSEL_PORT: 4242
            URL_BASE: ''
