annotations:
  truecharts.org/category: GIT
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
- alias: ''
  condition: memcached.enabled
  import-values: []
  name: memcached
  repository: oci://tccr.io/truecharts
  tags: []
  version: 13.0.13
deprecated: false
description: Self hosted GIT repositories
home: https://truecharts.org/charts/stable/gitea
icon: https://truecharts.org/img/hotlink-ok/chart-icons/gitea.webp
keywords:
- git
- issue tracker
- code review
- wiki
- gitea
- gogs
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: gitea
sources:
- https://gitea.com/gitea/helm-chart
- https://github.com/go-gitea/gitea
- https://github.com/truecharts/charts/tree/master/charts/stable/gitea
- https://hub.docker.com/r/gitea/gitea
type: application
version: 2025.1.26
