image:
  pullPolicy: IfNotPresent
  repository: piratify/invitarr
  tag: latest
persistence:
  config:
    enabled: true
    mountPath: /app/app/config
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            token: ''
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
