annotations:
  truecharts.org/category: media
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: IRC Highway eBook Downloads.
home: https://truecharts.org/charts/stable/openbooks
icon: https://truecharts.org/img/hotlink-ok/chart-icons/openbooks.webp
keywords:
- openbooks
- media
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: openbooks
sources:
- https://github.com/evan-buss/openbooks
- https://github.com/truecharts/charts/tree/master/charts/stable/openbooks
- https://hub.docker.com/r/evanbuss/openbooks
type: application
version: 2025.1.26
