image:
  pullPolicy: IfNotPresent
  repository: tccr.io/tccr/alpine
  tag: latest
kps:
  alertmanager:
    enabled: false
  coreDns:
    enabled: false
  crds:
    enabled: true
  defaultRules:
    create: false
  global:
    rbac:
      create: true
  grafana:
    defaultDashboardsEnabled: false
    enabled: false
    forceDeployDashboards: false
  kubeApiServer:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeDns:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeProxy:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeStateMetrics:
    enabled: false
  kubelet:
    enabled: false
  kubernetesServiceMonitors:
    enabled: false
  nodeExporter:
    enabled: false
  prometheus:
    enabled: false
  prometheus-windows-exporter:
    prometheus:
      monitor:
        enabled: false
  prometheusOperator:
    enabled: true
  thanosRuler:
    enabled: false
  windowsMonitoring:
    enabled: false
operator:
  register: true
portal:
  open:
    enabled: false
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    enabled: false
