annotations:
  truecharts.org/category: Other
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: Synchronize AdGuardHome config to replica instances.
home: https://truecharts.org/charts/stable/adguardhome-sync
icon: https://truecharts.org/img/hotlink-ok/chart-icons/adguardhome-sync.webp
keywords:
- adguardhome-sync
- Other
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: adguardhome-sync
sources:
- https://ghcr.io/bakito/adguardhome-sync
- https://github.com/bakito/adguardhome-sync/
- https://github.com/truecharts/charts/tree/master/charts/stable/adguardhome-sync
type: application
version: 2025.1.26
