image:
  pullPolicy: IfNotPresent
  repository: patrickstigler/quiz-game
  tag: latest
persistence:
  config:
    enabled: true
    mountPath: /app
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10588
        protocol: http
        targetPort: 80
