annotations:
  truecharts.org/category: media
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: dash. (or dashdot) is a modern server dashboard, running on the latest
  tech, designed with glassmorphism in mind.
home: https://truecharts.org/charts/stable/dashdot
icon: https://truecharts.org/img/hotlink-ok/chart-icons/dashdot.webp
keywords:
- dashboard
- dashdot
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: dashdot
sources:
- https://github.com/MauriceNino/dashdot
- https://github.com/truecharts/charts/tree/master/charts/stable/dashdot
- https://hub.docker.com/r/mauricenino/dashdot
type: application
version: 2025.1.26
