annotations:
  truecharts.org/category: home-automation
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: Home Assistant online configurator Chart from https://github.com/danielperna84/hass-configurator
home: https://truecharts.org/charts/stable/hassconfigurator
icon: https://truecharts.org/img/hotlink-ok/chart-icons/hassconfigurator.webp
keywords:
- hassconfigurator
- home-automation
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: hassconfigurator
sources:
- https://github.com/danielperna84/hass-configurator
- https://github.com/truecharts/charts/tree/master/charts/stable/hassconfigurator
- https://hub.docker.com/r/causticlab/hass-configurator-docker
type: application
version: 2025.1.26
