image:
  pullPolicy: IfNotPresent
  repository: flowko1/website-shot
  tag: latest
persistence:
  screenshots:
    enabled: true
    mountPath: /usr/src/website-shot/screenshots
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 1000
    runAsUser: 1000
service:
  main:
    ports:
      main:
        port: 10221
        targetPort: 3000
