annotations:
  truecharts.org/category: utilities
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: Docker registry v2 command line client and repo listing generator with
  security checks.
home: https://truecharts.org/charts/stable/reg
icon: https://truecharts.org/img/hotlink-ok/chart-icons/reg.webp
keywords:
- reg
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: reg
sources:
- https://github.com/genuinetools/reg
- https://github.com/k8s-at-home/container-images/
- https://github.com/truecharts/charts/tree/master/charts/stable/reg
- https://hub.docker.com/_/registry
type: application
version: 2025.1.26
