image:
  pullPolicy: IfNotPresent
  repository: remirigal/plex-auto-languages
  tag: latest
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PLEX_TOKEN: YOUR_TOKEN_PLEX
            PLEX_URL: http://plex:32400
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
