image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/linuxserver/calibre
  tag: latest
ingress:
  webserver:
    enabled: false
    targetSelector:
      webserver: webserver
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8084
        protocol: http
        targetPort: 8080
  webserver:
    enabled: true
    ports:
      webserver:
        enabled: true
        port: 8081
        protocol: http
        targetPort: 8081
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            CLI_ARGS: null
            PASSWORD: ''
