image:
  pullPolicy: IfNotPresent
  repository: hauxir/imgpush
  tag: latest
persistence:
  storagecache:
    enabled: true
    mountPath: /cache
  storageimages:
    enabled: true
    mountPath: /images
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 5000
        protocol: tcp
        targetPort: 5000
