image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/linuxserver/boinc
  tag: latest
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10142
        protocol: http
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PASSWORD: ''
