annotations:
  truecharts.org/category: management
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: Web-based LDAP browser to manage your LDAP server
home: https://truecharts.org/charts/stable/phpldapadmin
icon: https://truecharts.org/img/hotlink-ok/chart-icons/phpldapadmin.webp
keywords:
- phpldapadmin
- openldap
- userrights
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: phpldapadmin
sources:
- https://github.com/truecharts/charts/tree/master/charts/stable/phpldapadmin
- https://gitlab.v2.rancher.geohub.space/g3s/i3s/i3s-helm-catalog
- https://hub.docker.com/r/osixia/phpldapadmin
type: application
version: 2025.1.26
