image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/linuxserver/mysql-workbench
  tag: latest
persistence:
  config:
    enabled: true
    mountPath: /config
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    capabilities:
      add:
      - IPC_LOCK
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10134
        protocol: http
        targetPort: 3000
