image:
  pullPolicy: IfNotPresent
  repository: haveagitgat/tdarr_node
  tag: latest
persistence:
  configs:
    enabled: true
    mountPath: /app/configs
  logs:
    enabled: true
    mountPath: /app/logs
  media:
    enabled: true
    mountPath: /media
  transcode-cache:
    enabled: true
    mountPath: /temp
  varrun:
    enabled: true
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            nodeID: myFirstTdarrNode
            serverIP: 0.0.0.0
            serverPort: 8266
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
