image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/ctfd/ctfd
  tag: latest
mariadb:
  enabled: true
  includeCommon: true
  mariadbDatabase: ctfd
  mariadbUsername: ctfd
persistence:
  logs:
    enabled: true
    mountPath: /logs
  uploads:
    enabled: true
    mountPath: /uploads
portal:
  open:
    enabled: true
redis:
  enabled: true
  includeCommon: true
  redisUsername: default
service:
  main:
    ports:
      main:
        port: 10613
        protocol: http
        targetPort: 8000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DATABASE_HOST:
              secretKeyRef:
                expandObjectName: false
                key: plainhost
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
            DATABASE_NAME: '{{ .Values.mariadb.mariadbDatabase }}'
            DATABASE_PASSWORD: '{{ .Values.mariadb.password }}'
            DATABASE_PORT: 3306
            DATABASE_USER: '{{ .Values.mariadb.mariadbUsername }}'
            LOG_FOLDER: '{{ .Values.persistence.logs.mountPath }}'
            MAILFROM_ADDR: ''
            MAIL_PASSWORD: ''
            MAIL_PORT: 587
            MAIL_SERVER: ''
            MAIL_SSL: false
            MAIL_TLS: false
            MAIL_USEAUTH: false
            MAIL_USERNAME: ''
            OAUTH_CLIENT_ID: ''
            OAUTH_CLIENT_SECRET: ''
            REDIS_URL:
              secretKeyRef:
                expandObjectName: false
                key: url
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
            REVERSE_PROXY: false
            SAFE_MODE: true
            SECRET_KEY:
              secretKeyRef:
                key: SECRET_KEY
                name: ctfd-secrets
            UPLOAD_FOLDER: '{{ .Values.persistence.uploads.mountPath }}'
            UPLOAD_PROVIDER: filesystem
