annotations:
  truecharts.org/category: media
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: Overseerr is a free and open source software application for managing
  requests for your media library. It integrates with your existing services such
  as Sonarr, Radarr and Plex!
home: https://truecharts.org/charts/stable/overseerr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/overseerr.webp
keywords:
- overseerr
- plex
- sonarr
- radarr
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: overseerr
sources:
- https://ghcr.io/sct/overseerr
- https://github.com/sct/overseerr
- https://github.com/truecharts/charts/tree/master/charts/stable/overseerr
type: application
version: 2025.1.26
