annotations:
  truecharts.org/category: operators
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: system
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.0
- alias: cloudnative-pg
  condition: ''
  import-values: []
  name: cloudnative-pg
  repository: https://cloudnative-pg.github.io/charts
  tags: []
  version: 0.20.2
deprecated: false
description: CloudNativePG is a clustered postgresql database operator
home: https://truecharts.org/charts/system/cloudnative-pg
icon: https://truecharts.org/img/hotlink-ok/chart-icons/cloudnative-pg.webp
keywords:
- database
- cloudnative-pg
- cnpg
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: cloudnative-pg
sources:
- https://cloudnative-pg.io/
- https://github.com/cloudnative-pg
- https://github.com/truecharts/charts/tree/master/charts/system/cloudnative-pg
- https://github.com/truecharts/containers/tree/master/apps/alpine
type: application
version: 2025.1.26
