annotations:
  truecharts.org/category: system
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: A metrics exporter for TrueNAS
home: https://truecharts.org/charts/stable/truenas-exporter
icon: https://truecharts.org/img/hotlink-ok/chart-icons/truenas-exporter.webp
keywords:
- truenas-exporter
- metrics
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: truenas-exporter
sources:
- https://github.com/Supporterino/truenas-graphite-to-prometheus/tree/main
- https://github.com/truecharts/charts/tree/master/charts/stable/truenas-exporter
- https://hub.docker.com/r/prom/graphite-exporter
type: application
version: 2025.1.26
