annotations:
  truecharts.org/category: media
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: TagSpaces is an offline, open source, document manager with tagging support.
home: https://truecharts.org/charts/stable/tagspaces
icon: https://truecharts.org/img/hotlink-ok/chart-icons/tagspaces.webp
keywords:
- tagspaces
- documents
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: tagspaces
sources:
- https://github.com/tagspaces/tagspaces
- https://github.com/truecharts/charts/tree/master/charts/stable/tagspaces
- https://hub.docker.com/r/tagspaces/tagspaces-lite-web
type: application
version: 2025.1.26
