annotations:
  truecharts.org/category: media
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: Booksonic is a platform for accessing the audibooks you own wherever
  you are
home: https://truecharts.org/charts/stable/booksonic-air
icon: https://truecharts.org/img/hotlink-ok/chart-icons/booksonic-air.webp
keywords:
- booksonic
- audiobook
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: booksonic-air
sources:
- https://ghcr.io/linuxserver/booksonic-air
- https://github.com/popeen/Booksonic-Air
- https://github.com/truecharts/charts/tree/master/charts/stable/booksonic-air
type: application
version: 2025.1.26
