image:
  pullPolicy: IfNotPresent
  repository: jvmilazz0/kavita
  tag: latest
persistence:
  config:
    enabled: true
    mountPath: /kavita/config
  manga:
    enabled: true
    mountPath: /manga
  tmp:
    enabled: false
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10189
        targetPort: 5000
