image:
  pullPolicy: IfNotPresent
  repository: roxedus/ts-dnsserver
  tag: latest
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  dnsport:
    enabled: true
    ports:
      dnsport:
        enabled: true
        port: 53
        protocol: udp
        targetPort: 53
  main:
    ports:
      main:
        port: 5380
        protocol: http
        targetPort: 5380
