image:
  pullPolicy: IfNotPresent
  repository: binhex/arch-preclear
  tag: latest
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 6080
        protocol: tcp
        targetPort: 6080
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            VNC_PASSWORD: ''
            WEBPAGE_TITLE: Preclear
