annotations:
  truecharts.org/category: Administration
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: Aggregated management of TrueNAS devices
home: https://truecharts.org/charts/stable/truecommand
icon: https://truecharts.org/img/hotlink-ok/chart-icons/truecommand.webp
keywords:
- truecommand
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: truecommand
sources:
- https://github.com/truecharts/charts/tree/master/charts/stable/truecommand
- https://hub.docker.com/r/ixsystems/truecommand
type: application
version: 2025.1.26
