cloudflareddns:
  api_key: ''
  api_token: ''
  api_token_zone: ''
  detect_mode: dig-whoami.cloudflare
  detect_override: ''
  host_zone_record: []
  interval: 300
  log_level: 3
  user: your.cf.email@example.com
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/hotio/cloudflareddns
  tag: latest
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          env: {}
          envFrom:
          - secretRef:
              name: secret
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
